[theme]

# Primary accent for interactive elements
primaryColor = '#823921'

# Background color for the main content area
backgroundColor = '#1A0C0E'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#003450'

# Color used for almost all text
textColor = '#C3EBEF'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"